//shape 0:圆形;1:矩形;2:菱形;默认为1,
export const nodeList = [
    { id: "1", text: "开始", shape: 0, nodeId: "StartEvent_1k50257", x: 50 },
    { id: "2", text: "登记", nodeId: "Activity_13nint5", x: 200 },
    { id: "3", text: "运行确认", nodeId: "Activity_13gd96i", x: 350 },
    { id: "4", text: "二三类及其他", shape: 2, nodeId: "Gateway_16yrddw", x: 500 },
    { id: "5", text: "鉴定策划", nodeId: "Activity_1aabc3l", x: 650, y: 130 },
    { id: "6", text: "消缺", nodeId: "Activity_0btiby1", x: 650, },
    { id: "7", text: "流转", shape: 2, nodeId: "Gateway_1y9sgsm", x: 800 },
    { id: "7.1", text: "延期申请子流程", nodeId: "Activity_0mgz4rz", x: 650, y: 370 },
    { id: "7.2", text: "一类转二三类子流程", nodeId: "Activity_05e01rz", x: 800, y: 370 },
    { id: "7.3", text: "挂起申请子流程", nodeId: "Activity_0sht3mt", x: 950, y: 370 },
    { id: "8", text: "专工验收", nodeId: "Activity_0agmurh", x: 950, y: 60 },
    { id: "9", text: "场站负责人", nodeId: "Activity_0v8kouh", x: 950, y: 155 },
    { id: "10", text: "场站人员", nodeId: "Activity_0xjaw43", x: 950, },
    { id: "11", text: "结束", shape: 0, nodeId: "Event_1ae1lx9", x: 1100, },
];
export const linkList = [
    { from: "1", to: "2", styleClass: "lineStyle" },
    { from: "2", to: "3", styleClass: "lineStyle" },
    { from: "3", to: "4", styleClass: "lineStyle" },
    { from: "4", to: "5", text: '否', styleClass: "lineStyle", },
    { from: "4", to: "6", text: '是', styleClass: "lineStyle" },
    { from: "5", to: "6", styleClass: "lineStyle" },
    { from: "6", to: "7", styleClass: "lineStyle" },
    { from: "7", to: "7.1", text: '开始', styleClass: "lineStyle", },
    { from: "7", to: "7.2", text: '开始', styleClass: "lineStyle" },
    { from: "7", to: "7.3", text: '开始', styleClass: "lineStyle", },
    { from: "7", to: "8", text: '一类', styleClass: "lineStyle", },
    { from: "7", to: "9", text: '二类', styleClass: "lineStyle" },
    { from: "7", to: "10", text: '三类及其他', styleClass: "lineStyle", },
    { from: "8", to: "11", styleClass: "lineStyle" },
    { from: "9", to: "11", styleClass: "lineStyle" },
    { from: "10", to: "11", styleClass: "lineStyle" },
]